on: workflow_dispatch

jobs:
  build:
    permissions: write-all
    name: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [armv7-linux-androideabi, aarch64-linux-android]
        include:
          - arch: arm64-v8a
            target: aarch64-linux-android
          - arch: armeabi-v7a
            target: armv7-linux-androideabi

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup NDK
        run: |
          wget -nv https://dl.google.com/android/repository/android-ndk-r28b-linux.zip
          unzip -qo android-ndk-r28b-linux.zip
          chmod -R 777 ./android-ndk-r28b
          export NDK_HOME="$(pwd)/android-ndk-r28b"
          cargo install cargo-ndk
          mkdir -p htmlq/output

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build
        run: |
          cd htmlq
          cargo ndk -t ${{ matrix.arch }} -p 24 -- build --release -j $(nproc)
          mv -f target/${{ matrix.target }}/release/htmlq output/htmlq-${{ matrix.arch }}

      - id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          file: htmlq/output/*
          release_name: htmlq-ndk
          tag: ${{ steps.date.outputs.date }}
          overwrite: true
          file_glob: true
